### ISSUE TITLE
lsa_Lookup_Sids hanging?

### ISSUE THREAD

**Issue by winkaway** [BeyondTrust/pbis-open#25]
Hi,

I have a directory on my Linux server which contains 18 files, all of these files are owned by different users in a trusted Windows 2008 domain.  Some of these files are owned by users whose accounts have been deleted from the trusted Windows domain and therefore are not in the local PowerBroker cache or cannot be enumerated (or should I say, it requires a lookup request each time a directory listing is performed "ls -la").

After performing a TCP capture I can see that each time a "ls -la" is performed on this directory an SMB request (lsa_Lookup_Sids) is sent to the domain controller to try and resolve the UID to a friendly username.  Obviously a friendly username is never returned because the user does not exist and the long listing just shows the UID, this is not a problem and expected behavior.

The problem occurs if you run the directory listing "ls -la" a few times one after each other, eventually the console (ssh session) will hang (ctrl + c, nothing works) and no directory listing or anything is returned until 300 seconds later when the TCP (SMB) session times out and a new session SMB session is established, then all of a sudden the session comes to life and the directory listing is displayed.

Your answer might be to remove the files owned by orphaned users but I have really simplified my description of the issue because this is happening across an estate of ~30 servers with many different directories and keeping on top of this would be an admin nightmare, so the real answer would be to address why this is hanging when lsa_Lookup_Sids are sent to the DC?

Is there any debugging / logging we can enable to see what the process is doing when these directory long listings are issued?
Are there any ways to address orphaned files (where the user has been deleted) so that we don't have the expensive lsa_Lookup_Sids being run everytime a process / user requests a directory?

Client OS:
Red Hat Enterprise Linux Server release 6.6

PB open version:
Compiled daemon version: 8.3.0.3287
Packaged product version: 8.3.3287.68880

DC OS:
Windows 2008 R2 STD with one way transitive trust relationship

Thanks for your time,

**Comment by rbest-bt** [comment]
Can you try and upgrade to the latest version - [8.5.3](https://github.com/BeyondTrust/pbis-open/releases/tag/8.5.3) - and see if the issue continues?

I believe this issue was fixed around 8.3.3

**Comment by winkaway** [comment]
1) I performed an upgrade of PB Open to 8.5.3 but the problem persisted.
2) I also performed a clean installation of Redhat 6.9 (this time with all yum updates) and installed PB Open 8.5.3 but again the problem is still there.

Do you have any reference to this issue when it was first fixed?  Maybe I can try to replicate the debugging to see if the problem is in fact the same?

Confirmation of the PB Open version
Compiled daemon version: 8.5.3.293
Packaged product version: 8.5.293.0

**Comment by RBoulton-BT** [comment]
I think although the bug description was very similar this may be a separate issue. I have also been experiencing similar issues with DCE/RPC over SMB in recent weeks and will be investigating the root cause. In my situation adtool would hang after performing many repeated DCE/RPC over SMB calls and then the session times out like you describe. I'm not sure what could have changed to cause this to start happening though.

**Comment by winkaway** [comment]
This issue has been occurring for some time on our systems.  
Please let me know if I can provide any information to help in this investigation?

**Comment by winkaway** [comment]
@RBoulton-BT, did you have any luck investigating this DCE/RPC issue?

**Comment by RBoulton-BT** [comment]
It's high on our backlog but unfortunately other priorities are currently taking our development resources. We have been able to consistently reproduce the hang, it seems to be in the LWIO/RDR code and looks like some sort of thread synchronization/lock type issue, but we have been unable to get much further.

**Comment by winkaway** [comment]
After further investigations it looks like some of the files are in fact not orphans but rather PB Open is not resolving their UID / GID to a human readable names but some files are.  Ie: user accounts in the PB cache look to be okay but any other accounts seem to have an issue.  This is until I run"id username" on one of the accounts which I know is a legitimate user and the owner of one or more of the files in the directory, then it resolves and the PB cache is populated with the user and any further ls -la requests no longer need to send RPC requests.

I am therefore looking to find a workaround for this issue while you guys work through your backlog of current issues.
Would you suggest running "id username" on all of the user accounts in /home/local/<DOMAIN> every couple of hours to keep them in the local PB cache?  By default the local cache expires after 4 hours, does this mean if I were to query a user every hour with "id username" it would still expire after 4 hours or does the timer get reset?
Are there any other commands you could suggest to cobble together a script to mitigate this issue and keep users and groups in the local PB cache?
Remember, these are accounts in a trusted Windows domain in a separate forest.

Thanks again for all your efforts.

**Comment by rbest-bt** [comment]
There have been improvements to this in Enterprise. Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
